name: CD Pipeline

on:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout Code
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Download Image Tag Artifact
    - name: Download Image Tag Artifact from CI
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        CI_RUN_ID=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/runs \
        | jq -r '.workflow_runs[] | select(.name=="CI Pipeline") | .id' | head -n1)
        echo "Found CI Workflow Run ID: $CI_RUN_ID"

        IMAGE_TAG_ARTIFACT_URL=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/runs/$CI_RUN_ID/artifacts \
        | jq -r '.artifacts[] | select(.name=="image-tag") | .archive_download_url')

        echo "Downloading Image Tag Artifact: $IMAGE_TAG_ARTIFACT_URL"
        curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -L -o image-tag.zip $IMAGE_TAG_ARTIFACT_URL
        unzip image-tag.zip

    - name: Read Image Tag
      run: |
        IMAGE_TAG=$(cat image_tag.txt)
        echo "Image Tag: $IMAGE_TAG"
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    # 3. Download Helm Chart Artifact
    - name: Download Helm Chart Artifact from CI
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        CI_RUN_ID=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/runs \
        | jq -r '.workflow_runs[] | select(.name=="CI Pipeline") | .id' | head -n1)
        echo "Found CI Workflow Run ID: $CI_RUN_ID"

        HELM_CHART_ARTIFACT_URL=$(gh api -H "Accept: application/vnd.github+json" /repos/${{ github.repository }}/actions/runs/$CI_RUN_ID/artifacts \
        | jq -r '.artifacts[] | select(.name=="helm-chart") | .archive_download_url')

        echo "Downloading Helm Chart Artifact: $HELM_CHART_ARTIFACT_URL"
        curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -L -o helm-chart.zip $HELM_CHART_ARTIFACT_URL
        unzip helm-chart.zip

    # 4. Install kubectl
    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    # 5. Set Up kind
    - name: Set up kind
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind
        kind create cluster --name test-cluster

    # 6. Install Helm
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    # 7. Deploy Application with Downloaded Helm Chart
    - name: Deploy Application with Helm
      env:
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
      run: |
        ls -R ./packaged-charts/
        helm upgrade --install flask-app ./packaged-charts/app-*.tgz \
          --set image.repository=${{ secrets.DOCKER_USERNAME }}/flask-app \
          --set image.tag=${IMAGE_TAG} \
          --set image.pullPolicy=Always \
          --set service.type=NodePort

    # 8. Test Application
    - name: Test Application
      run: |
        echo "Waiting for the pod to be ready..."
        POD_NAME=""
        for _ in {1..5}; do
          POD_NAME=$(kubectl get pods -l app=app -o jsonpath="{.items[0].metadata.name}" 2>/dev/null || echo "")
          [[ -n "$POD_NAME" ]] && STATUS=$(kubectl get pod $POD_NAME -o=jsonpath='{.status.phase}') || STATUS=""
          if [[ "$STATUS" == "Running" ]]; then
            echo "Pod is running: $POD_NAME"
            break
          fi
          echo "Pod status: $STATUS. Retrying in 5 seconds..."
          sleep 5
        done

        if [[ "$STATUS" != "Running" ]]; then
          echo "Error: Pod did not start within the expected time."
          exit 1
        fi

        echo "Setting up port forwarding..."
        kubectl port-forward pod/$POD_NAME 5001:5001 &
        sleep 5
        echo "Testing the application..."
        RESPONSE=$(curl --retry 5 --retry-delay 5 -s -w "\n%{http_code}" http://localhost:5001/)
        BODY=$(echo "$RESPONSE" | sed '$d')
        STATUS_CODE=$(echo "$RESPONSE" | tail -n1)
        echo "Response Body: $BODY"
        echo "HTTP Status Code: $STATUS_CODE"

    # 9. Clean Up
    - name: Delete kind Cluster
      run: kind delete cluster --name test-cluster
