name: CI/CD Pipeline

on:
  push:
    branches:
      - ci-pipeline-setup  # Trigger on pushes to the main branch

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout Code
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Install Dependencies and Test
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r app/requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/app" >> $GITHUB_ENV
      
    - name: Run tests
      run: pytest app/tests

    # 3. Build Docker Image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/flask-app:latest .

    # 4. Push Docker Image
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image to DockerHub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

    # 5. Deploy Using Helm
    # - name: Deploy to Kubernetes
    #   env:
    #     IMAGE_TAG: latest
    #   run: |
    #     helm upgrade --install flask-app ./helm/flask-app \
    #       --set image.repository=${{ secrets.DOCKER_USERNAME }}/flask_app \
    #       --set image.tag=${IMAGE_TAG} \
    #       --set replicaCount=1
